Add Alpine Linux CI and stop enabling werror for everyone
linux-msm/cdba pull request #37
Opened 2023-10-19 23:00 UTC by calebccff

Enabling -Werror by default sucks for everyone who isn't maintaining
CDBA. By all means we should enable it in CI, but not for users and
not for folks packaging it in distros.

Remove it from the flags in meson.build, and use mesons built in option
to enable it only in CI.

See:
https://embeddedartistry.com/blog/2017/05/22/werror-is-not-your-friend/

I plan to package CDBA in Alpine soon, having build tests for it in CI will help ensure that we avoid easy regressions like missing headers (yay musl..)

2023-10-23 07:49 UTC, lumag commented
@calebccff could you please fix the error reported on Debian / buster?

2023-10-23 10:27 UTC, calebccff commented
i realise i did almost exactly what you have in

https://github.com/linux-msm/cdba/pull/35

if you want to just merge that I'll adjust this pr to just add alpine CI

2023-10-30 09:27 UTC, superna9999 approved these changes

2023-10-30 09:28 UTC, superna9999 commented on .github/workflows/ci.yml
> +        meson setup --errorlogs --werror . build
Why did you add --errorlogs only here ?

2023-10-30 15:10 UTC, superna9999 requested changes

2023-10-30 15:10 UTC, superna9999 commented on .github/workflows/ci.yml
> +        CFLAGS="-m32" LDFLAGS="-m32" meson setup --werror . build
This should go in the previous patch

2023-10-30 15:10 UTC, superna9999 commented on .github/workflows/ci.yml
> +        meson setup --werror --cross-file cross.txt . build
This should go in the previous patch

2023-11-02 08:41 UTC, lumag requested changes
@calebccff could you please follow @superna9999 's suggestions?

2023-11-06 12:25 UTC, lumag approved these changes

2023-11-06 12:34 UTC, superna9999 approved these changes
LGTM

2023-11-06 12:34 UTC, merged